awesome-academy/pr1909-group1

app/mailers/application_mailer.rb, app/models/user.rb, config/environments/development.rb, db/migrate/20200407163746_devise_create_users.rb, db/schema.rb, db/seeds.rb
=> add module confirmable of gem devise, send mail active and reset password

app/controllers/registrations_controller.rb, app/models/employer.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, config/routes.rb, config/settings.yml, db/migrate/20200407170806_add_name_and_user_type_to_user.rb, db/migrate/20200410112734_create_candidates.rb, db/schema.rb, db/seeds.rb
Thay đổi:
- tạo candidate và employer sau khi sign up user
- sửa lại setting cho hợp lý hơn
=> create employer or candidate after sign up

app/controllers/job_posts_controller.rb, app/models/employer.rb, app/models/job_post.rb, app/views/job_posts/_form.html.erb, app/views/job_posts/index.html.erb, app/views/job_posts/index.json.jbuilder, app/views/job_posts/show.html.erb, app/views/job_posts/show.json.jbuilder, config/settings.yml, test/controllers/job_posts_controller_test.rb
thêm crud cho job post
thay đổi một số validation job_post
#17 
chỉnh sửa view tạm thời cho show, edit job post
=> [Common][BE&FE] CRUD job post and add validation

README.md
CHange README to test auto deploy heroku
=> demo change README_test auto deploy

app/controllers/application_controller.rb, app/controllers/job_posts_controller.rb, app/helpers/job_posts_helper.rb, app/models/apply_activity.rb, app/models/candidate.rb, app/models/job_post.rb, app/views/job_posts/index.html.erb, app/views/job_posts/show.html.erb, config/routes.rb, db/migrate/20200421014509_create_apply_activities.rb, db/schema.rb, db/seeds.rb, test/fixtures/apply_activities.yml, test/models/apply_activity_test.rb
add and validate model ApplyActivity
change root
add relative model ApplyActivity to others
add job post helper
change jobpost#index to show all job post
add seed data JobPost and ApplyActivity
#22
=> [JOBPOST][BE&FE] add apply activity and fix bug

Gemfile, Gemfile.lock, app/assets/stylesheets/custom.scss, app/assets/stylesheets/footer.scss, app/assets/stylesheets/header.scss, app/controllers/application_controller.rb, app/controllers/candidates_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, config/application.rb, config/locales/en.yml, config/locales/vi.yml, config/routes.rb, db/schema.rb
Add I18n for view header,footer and model devise
1. Add and config gem 'rails I18n'
2. Use I18n for header,footer 
3. User gem 'devise i18n' for view devise and change form
4. Fix footer to bottom of page
=> [FE&BE][Common] Add I18n for view header,footer and view devise

app/assets/stylesheets/custom.scss, app/assets/stylesheets/employer.scss, app/views/devise/registrations/edit.html.erb, app/views/employers/_form.html.erb, app/views/employers/edit.html.erb, app/views/employers/index.html.erb, app/views/employers/show.html.erb, app/views/job_posts/index.html.erb, app/views/shared/_header.html.erb, config/locales/en.yml, config/locales/vi.yml, config/settings.yml, db/seeds.rb
Custom view index-show-edit employer
1. Custom view index-show-edit employer (responsive)
2. I18n will_paginate
3. Add show all employer to header
4. Change some in file seed.rb
1. @hiennghiem: show job_post for current employer (view show employer)
2. add button create job_post in view index (root) if user is a employer
=> [Frontend][Employer] Custom view employer

app/controllers/apply_activities_controller.rb, app/helpers/job_posts_helper.rb, app/models/candidate.rb, app/models/job_post.rb, app/views/apply_activities/create.js.erb, app/views/apply_activities/destroy.js.erb, app/views/job_posts/_apply.html.erb, app/views/job_posts/_apply_form.html.erb, app/views/job_posts/_apply_not_login.html.erb, app/views/job_posts/_cancel_application.html.erb, app/views/job_posts/_card.html.erb, app/views/job_posts/show.html.erb, config/locales/en.yml, config/locales/vi.yml, config/routes.rb, db/schema.rb
thêm chức năng ứng tuyển công việc.
chia 3 trường hợp:
khi chưa login nhấn ứng tuyển sẽ quay lại trang đăng nhập
khi là employer sẽ k hiện nút ứng tuyển.
khi là candidate sẽ có thể ứng tuyển và hủy ứng tuyển
=> [BE] feature apply job

app/controllers/candidates_controller.rb, app/controllers/employers_controller.rb, app/controllers/job_posts_controller.rb
=> fix perpage to per_page

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/datetimepicker.js, app/assets/stylesheets/candidate.scss, app/assets/stylesheets/custom.scss, app/assets/stylesheets/job_post.scss, app/controllers/employers_controller.rb, app/views/candidates/_form.html.erb, app/views/candidates/edit.html.erb, app/views/candidates/show.html.erb, app/views/employers/index.html.erb, app/views/employers/show.html.erb, app/views/job_posts/_card.html.erb, app/views/job_posts/_form.html.erb, app/views/job_posts/edit.html.erb, app/views/job_posts/index.html.erb, app/views/job_posts/new.html.erb, app/views/job_posts/show.html.erb, config/locales/en.yml, config/locales/vi.yml, db/migrate/20200417074116_create_job_posts.rb, db/schema.rb, db/seeds.rb
Change view job_post,candidate and use datetimepicker
1. Change view job_post,candidate
2. Use gem 'bootstrap3-datetimepicker-rails' for attributes job_expired_date and date_of_birth
3. Use URI tel: for contact candidate
4. Schema.rb : delete "default: 1" for attributes job_location
5. i18n
Candidate
Employer
User
=> [FE][Job_Post][Candidate] Change view job_post,candidate and use datetimepicker

db/seeds.rb
=> fix seed data heroku

app/assets/javascripts/notification.js, app/assets/stylesheets/custom.scss, app/assets/stylesheets/devise.scss, app/assets/stylesheets/employer.scss, app/controllers/registrations_controller.rb, app/models/employer.rb, app/views/candidates/_form.html.erb, app/views/candidates/show.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/employers/_form.html.erb, app/views/employers/show.html.erb, app/views/job_posts/_form.html.erb, app/views/job_posts/show.html.erb, app/views/layouts/_messages.html.erb, app/views/layouts/application.html.erb, app/views/layouts/job_posts.html.erb, config/locales/en.yml, config/locales/vi.yml, db/migrate/20200410112749_create_employers.rb, db/schema.rb
Fix bug:
No2: Thông báo lỗi đang bị lệch, và ẩn đi sau một khoảng thời gian
No3: Remember me hơi sát với check box
No5: Hạn chế việc sử dụng câu hỏi trong website
No7: Text lỗi sai màu
No8: Đổi You are ở phần sign up thành role
No10 & No11: fix ở #39 
1. Fix bug No2,3,5,7,8,10,11
2. Đổi tên method update_resource -> update_resource_new, và không cho thay đổi email khi edit user
3. Thêm validate cho 2 trường company_size và company_name, presence: true
Chưa fix được i18n cho notice và alert (tất cả đang là EN ngoại trừ một số cái của view devise do có dùng gem devise-i18n)
=> [FixBug][Common] fix bug No2,3,5,7,8,10,11

app/assets/javascripts/pagination.js, app/assets/stylesheets/modal_candidate.scss, app/controllers/apply_activities_controller.rb, app/controllers/candidates_controller.rb, app/controllers/job_posts_controller.rb, app/views/apply_activities/_applied_candidates.html.erb, app/views/apply_activities/_index.html.erb, app/views/apply_activities/index.html.erb, app/views/apply_activities/index.js.erb, app/views/job_posts/show.html.erb, config/locales/en.yml, config/locales/vi.yml, config/routes.rb
thêm chức năng cho phép employer xem các candidate đã ứng tuyển vào job hiện tại
sử dụng modal show applied candidate
=> [BE&FE]show applied candidates

app/assets/javascripts/validate_email.js, app/models/user.rb, app/views/devise/registrations/new.html.erb
validate first_name và last_name chỉ bao gồm ký tự
validate email bằng javascript
=> [BE&FE]add validate name in model and validate mail by javascript

Gemfile, Gemfile.lock, app/assets/javascripts/validate_email.js, app/assets/stylesheets/apply_activities.scss, app/assets/stylesheets/devise.scss, app/assets/stylesheets/job_post.scss, app/controllers/apply_activities_controller.rb, app/controllers/employers_controller.rb, app/models/apply_activity.rb, app/views/apply_activities/_applied_candidates.html.erb, config/locales/en.yml, config/locales/vi.yml, config/routes.rb, db/migrate/20200519085259_add_aasm_state_to_apply_activities.rb, db/schema.rb
1. Feature: State machines for model apply activity
1. Add gem assm
2. Use state machines for model apply activity
3. Css view
=> [BE&FE][Apply_activity] Add gem aasm and use state machines for model apply activity

app/assets/stylesheets/application.css, app/controllers/home_controller.rb, app/javascript/packs/application.js, app/views/home/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_header.html.erb, config/routes.rb, config/webpack/environment.js, package.json, yarn.lock
Create home page,header and add boostrap4
1. Create controller and view home
2. install webpacker bootstrap
#64
=> [Common] Create home page,header and add boostrap4

Gemfile, Gemfile.lock, app/assets/stylesheets/about.scss, app/assets/stylesheets/courses.scss, app/assets/stylesheets/custom.scss, app/controllers/courses_controller.rb, app/controllers/home_controller.rb, app/javascript/packs/application.js, app/javascript/packs/pagination.js, app/views/courses/_courses_all.html.slim, app/views/courses/_form.html.slim, app/views/courses/edit.html.slim, app/views/courses/index.html.slim, app/views/courses/index.js.slim, app/views/courses/new.html.slim, app/views/courses/show.html.slim, app/views/home/_about.html.slim, app/views/home/_count_course.html.slim, app/views/home/index.html.slim, app/views/shared/_banner.html.slim, app/views/shared/_footer.html.slim, app/views/shared/_header.html.slim, config/locales/en.yml, config/locales/vi.yml, config/settings.yml, db/seeds.rb
I18N view edit, new course, about, count
1. I18N view edit, new course, about, count
2. add gem 'will_paginate-bootstrap4'
3. add gem faker fake data
#73 
Em đang comment lại cái tính năng ajax cho pagination @@
=> [Common] I18N view edit,new course

app/assets/stylesheets/courses.scss, app/controllers/courses_controller.rb, app/models/course.rb, app/models/course_type.rb, app/models/evaluate_course.rb, app/models/register.rb, app/models/review_course.rb, app/models/user.rb, app/views/admin/courses/_form.html.slim, app/views/courses/_courses_all.html.slim, app/views/courses/show.html.slim, config/settings.yml, db/migrate/20200612113415_create_courses.rb, db/migrate/20200617040655_create_course_types.rb, db/migrate/20200617041431_create_review_courses.rb, db/migrate/20200617050851_create_registers.rb, db/migrate/20200617083708_add_course_type_to_course.rb, db/migrate/20200617092100_create_evaluate_courses.rb, db/schema.rb, db/seeds.rb
thêm và validate model course_type, register, review_course, evaluate_course
thêm relationship giữa các model
thêm seed data
update: 21/6/2020
em remove trường star vì team thống nhất làm like để đánh giá khóa học ạ.
=> [BE]Feature/create model course_type register review_course

app/assets/stylesheets/admin.scss, app/controllers/admin/sessions_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/application_controller.rb, app/models/admin.rb, app/models/user.rb, app/views/admin/base/index.html.slim, app/views/admin/courses/show.html.slim, app/views/admin/sessions/new.html.erb, app/views/admin/users/_form.html.slim, app/views/admin/users/_user.json.jbuilder, app/views/admin/users/_users_all.html.slim, app/views/admin/users/edit.html.slim, app/views/admin/users/index.html.slim, app/views/admin/users/index.js.slim, app/views/admin/users/index.json.jbuilder, app/views/admin/users/new.html.slim, app/views/admin/users/show.html.slim, app/views/admin/users/show.json.jbuilder, app/views/devise/sessions/new.html.erb, app/views/home/index.js.slim, app/views/layouts/admin/_admin_navbar.html.slim, app/views/layouts/admin/_admin_sidebar.html.slim, app/views/layouts/admin/admin_login.html.slim, config/routes.rb
1. Admin crud user
2. Page login admin
#85 
- I18n page admin
=> [BE&FE][Admin] Admin crud user and page login admin

app/assets/stylesheets/courses.scss, app/assets/stylesheets/custom.scss, app/controllers/courses_controller.rb, app/controllers/registers_controller.rb, app/helpers/courses_helper.rb, app/models/register.rb, app/models/user.rb, app/views/courses/_courses_all.html.erb, app/views/courses/_register_course.html.erb, app/views/courses/_register_not_login.html.erb, app/views/courses/_registered.html.erb, app/views/courses/_show_student.html.erb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/registers/create.js.erb, config/locales/en.yml, config/locales/vi.yml, config/routes.rb, db/migrate/20200626172348_add_total_registers_count_to_courses.rb, db/schema.rb, db/seeds.rb
Tính năng đăng ký khóa học cho user
#94
=> [BE][Course] Register course

app/assets/stylesheets/lesson_form.scss, app/javascript/packs/admin_course.js, app/models/lesson.rb, app/views/admin/courses/_form.html.slim, app/views/admin/courses/_lesson_form.html.slim, app/views/admin/courses/new.html.slim, app/views/lessons/_question.html.slim, app/views/lessons/_quiz.html.slim, app/views/lessons/_quiz_form.html.slim, app/views/quiz_results/_fail_modal.html.slim, app/views/quiz_results/_result.html.slim, config/locales/en.yml, config/locales/vi.yml
fix bug khi xóa lesson ở giữa sau đó thêm lesson sẽ bị lặp tên.
thêm I18N
=> [FE] add I18N in show lessons and fix bug create course

app/assets/stylesheets/admin.scss, app/assets/stylesheets/admin_course.scss, app/assets/stylesheets/courses.scss, app/controllers/admin/courses_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/courses_controller.rb, app/controllers/registers_controller.rb, app/javascript/packs/pagination.js, app/views/admin/base/index.html.slim, app/views/admin/courses/_courses_all.html.slim, app/views/admin/courses/show.html.slim, app/views/admin/users/_users_all.html.slim, app/views/courses/_register_course.html.erb, app/views/courses/_show_student.html.erb, app/views/courses/show.html.erb, app/views/courses/show.js.erb, app/views/layouts/admin/_admin_navbar.html.slim, app/views/layouts/admin/_admin_sidebar.html.slim, app/views/lessons/_video.html.erb, app/views/lessons/show.js.erb, app/views/registers/create.js.erb, app/views/registers/update.js.erb, app/views/review_courses/_comments.html.slim, config/locales/en.yml, config/locales/vi.yml, config/settings.yml, db/migrate/20200612113415_create_courses.rb, db/schema.rb, db/seeds.rb
ListBug https://docs.google.com/spreadsheets/d/1Y_LeyRkSTyifMN5qTKVOofdjYUy8z3EbLoPPDFUFtbQ/edit#gid=0
=> [Common] Fix bug

Gemfile, Gemfile.lock, app/assets/stylesheets/courses.scss, app/assets/stylesheets/header.scss, app/controllers/courses_controller.rb, app/controllers/quiz_results_controller.rb, app/models/course.rb, app/views/courses/_search_course.html.erb, app/views/courses/search.html.erb, app/views/courses/search.js.erb, app/views/courses/show.html.erb, app/views/shared/_header.html.slim, config/locales/en.yml, config/locales/vi.yml, config/routes.rb, config/settings.yml
thêm gem searchkick
sử dụng elasticsearch để search course theo course_type và course_title
để chạy được elasticsearch cần cài java jdk. link hướng dẫn cài java jdk
https://stackjava.com/install/cai-dat-java-tren-linux-ubuntu-oracle-jdk-open-jdk.html
nếu cài theo bài hướng dẫn bị lỗi thì có thể tham khảo bài này
https://linuxize.com/post/install-java-on-ubuntu-18-04/
hướng dẫn cài đặt elasticsearch
https://stackjava.com/elasticsearch/huong-dan-cai-dat-elasticsearch-tren-ubuntu-16-04.html
sau khi cài xong elasticsearch thì vào rails console chạy lệnh Course.reindex
=> [BE&FE] search course

app/assets/stylesheets/admin_course.scss, app/controllers/admin/courses_controller.rb, app/models/course.rb, app/views/admin/courses/_form.html.slim, app/views/admin/courses/create.js.erb, app/views/admin/courses/edit.html.slim, app/views/admin/courses/update.js.erb, app/views/shared/_error_messages.html.erb
ajax cho trang tạo khóa học và edit khóa học
=> [BE&FE] ajax for create edit course
